<?php

/**
 * @file
 * Template preprocess functions that help modify the HTML for UI Kit.
 */

use Drupal\govcms_uikit\Error\UikitInvalidRenderArray;

/**
 * Implements hook_preprocess_views_view_table().
 */
function govcms_uikit_preprocess_views_view_table(&$variables) {
  /** @var \Drupal\govcms_uikit\Service\Table $service */
  $service = \Drupal::service('govcms.uikit.table');

  try {
    $service->alter($variables);
  }
  catch (UikitInvalidRenderArray $exception) {
    // @TODO: Consider logging the error.
  }
}

/**
 * Implements hook_preprocess_table().
 */
function govcms_uikit_preprocess_table(&$variables) {
  /** @var \Drupal\govcms_uikit\Service\Table $service */
  $service = \Drupal::service('govcms.uikit.table');

  try {
    $service->alter($variables);
  }
  catch (UikitInvalidRenderArray $exception) {
    // @TODO: Consider logging the error.
  }

}
