<?php

/**
 * @file
 * Template preprocess functions that help modify the HTML for UI Kit.
 */

/**
 * Implements hook_preprocess_views_view_table().
 */
function govcms_uikit_preprocess_views_view_table(&$variables) {
  /** @var \Drupal\govcms_uikit\Service\Table $service */
  $service = \Drupal::service('govcms.uikit.table');
  $service->alter($variables);
}

/**
 * Implements hook_preprocess_table().
 */
function govcms_uikit_preprocess_table(&$variables) {
  /** @var \Drupal\govcms_uikit\Service\Table $service */
  $service = \Drupal::service('govcms.uikit.table');
  $service->alter($variables);
}
